@FIREBASE_API_KEY = AIzaSyCa0z_T4qXgmGQmuTRg4iHpMKGxLI5oZyk

@EMAIL = nperez@uniempresarial.edu.co
@PASSWORD = 123456+
@BACKEND_URL = http://127.0.0.1:8000

### 1. INICIAR SESIÓN EN FIREBASE
# @name firebaseLogin
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={{FIREBASE_API_KEY}}
Content-Type: application/json
Accept: application/json

{
  "email": "{{EMAIL}}",
  "password": "{{PASSWORD}}",
  "returnSecureToken": true
}

### CONSULTAR MATERIAL CON EL TOKEN OBTENIDO
GET {{BACKEND_URL}}/api/v1/materials/
Authorization: Bearer {{firebaseLogin.response.body.$.idToken}}
Accept: application/json

### CREAR UN MATERIAL NUEVO CON EL TOKEN OBTENIDO
POST {{BACKEND_URL}}/api/v1/materials/
Authorization: Bearer {{firebaseLogin.response.body.$.idToken}}
Content-Type: application/json
Accept: application/json

{
  "material_type": "Piel de durazno",
  "quantity": 30,
  "unit": "metros",
  "color": "rosado",
  "densidad": "media",
  "status": "available",
  "published_by": "demo-owner"
}

### EDITAR UN MATERIAL NUEVO CON EL TOKEN OBTENIDO
PUT {{BACKEND_URL}}/api/v1/materials/6aa340d2372cc2b4cc1ab3b5/
Authorization: Bearer {{firebaseLogin.response.body.$.idToken}}
Content-Type: application/json
Accept: application/json

{
  "material_type": "Algodón perchado",
  "quantity": 500,
  "unit": "metros",
  "color": "negro",
  "densidad": "muy pesado",
  "status": "available"
}

### ELIMINAR MATERIAL CON EL TOKEN OBTENIDO
DELETE {{BACKEND_URL}}/api/v1/materials/<6aa33d81686523a027278608>/
Authorization: Bearer {{firebaseLogin.response.body.$.idToken}}
Accept: application/json